const LANG_EN = {
  component: {
    h_1: 'Vision',
    h_2: 'Robot',
    h_3: 'Robot Application',
    h_4: 'Vision Application',
    h_5: 'History & Team Culture',
    h_6: 'korean',
    f_1: 'CEO',
    f_2: 'EunHo Kim',
    f_3: 'HEAD OFFICE',
    f_4: 'Room 2-1, B2, Center A, Software Dream Center, 20, Changeop-ro 40beon-gil, Sujeong-gu, Seongnam-si, Gyeonggi-do, Republic of Korea',
    f_5: 'R&D Center',
    f_6: 'Room 201, 2nd Floor, ChangDong Arune, 84, Madeul-ro 13-gil, Dobong-gu, Seoul, Republic of Korea',
    f_7: 'E-mail',
    f_8: 'Number'
  },
  main_page: {
    main_banner_sub: "We revolutionize manufacturing through digital twin technology and AI",
    vision_main: "Transform your production line with Fake Shot Learning, enabling rapid setup of product inspection environments tailored to your specific manufacturing processes",
    vision_sub: "Fake Shot Learning : An AI model training method based on generated virtual data",
    robot_main: "Build a fully automated collaborative robot line with flexible task generation and a user-friendly control UI tailored for your needs",
    robot_sub: "Flexible Task Generation : Behavior-based next-generation robot motion generation method",
  },
  tech: {
    tech_1: "Collaborative Robot with Integrated Vision Inspection Camera",
    tech_2: "Object recognition powered by image-based AI models",
    tech_3: "Analysis of the work environment, object recognition, and decision-making, Scene Graph Generation & Understanding",
    tech_4: "Development of Dynamic Path Generation Technology",
    tech_5: "Gathering cognitive information in response to situational changes and generating dynamic robot paths",
    tech_6: "Creating baseline paths using 6-DOF sensors",
    tech_7: "Path re-planning and trajectory optimization",
    tech_8: "Dynamic Object Vision Inspection (Conveyor Tracking)",
    tech_9: "Extracting vision inspection points for dynamic objects, Generating dynamically optimized robot imaging paths",
    tech_10: "AI Vision Inspection",
    tech_11: "Fake-shot learning to reduce false defects",
    tech_12: "Generation of virtual defect data and creation of fake-shot AI models",
    tech_13: "6D Pose Recognition of Objects",
    tech_14: "Estimation of 6D poses using 3D CAD object dataand generating dynamic robot paths",
    tech_15: "Tracking and predicting the movement paths of dynamic objects",
    tech_16: "Robot vision coordinate transformation and object data calculation relative to the robot",
    tech_17: "Measurement Inspection, Visual Inspection",
    tech_18: "Detection of product finish and alignment defects (e.g., size, shape, and alignment angle)",
    tech_19: "Identification of product contamination and color defects (e.g., scratches, foreign materials, cracks, and uniform color inspection)",
  }
}